### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by Enzotoy** [davidteather/BackpackTf-API#4]
Hello, i have this error on you module:

![image](https://user-images.githubusercontent.com/39483959/70229196-fe0ac880-1755-11ea-89a3-35ec9a5e193b.png)

@davidteather, thank you for reply.

**Comment by davidteather** [comment]
You’re using python 2.7 to run the script when it is only designed for python 3.x. Try 
python3 bot.py

**Comment by Enzotoy** [comment]
Thank, it's work, But we can't get the buy oder and sell oder price?

**Comment by davidteather** [comment]
Can you show me the code you’re running?

**Comment by Enzotoy** [comment]
![image](https://user-images.githubusercontent.com/39483959/70243559-1806d400-1773-11ea-8e99-3cc0cd4b7d7c.png)

there is, i'm new to python and i trying to put the price on a json file to make a "if" like that:

if sell_oder < buy_oder
   print("match found!")

**Comment by davidteather** [comment]
Since there's different requirements beyond just currency, to get listings you need to make an instance of the Account class.

You need to go to register a BackpackTF app [here](https://backpack.tf/developer/apps) and use the app details and plug them in below.

```
from BackpackTF import Account

user = Account(client_id="xxxxxxxxx", client_secret="xxxxxxxxxx", api_key="xxxxxxxxxx")

user.search_classifieds(intent="both")
```

There are a few other required fields when searching for classifieds that can be found [here](https://github.com/davidteather/BackpackTf-API#search_classifieds---searches-for-classifieds)

**Comment by Enzotoy** [comment]
Thank but with your code, i have this error now
![image](https://user-images.githubusercontent.com/39483959/70268613-223fc700-17a1-11ea-8efa-6c4cb60d6639.png)
i tried the code on a VM but i get the same error

**Comment by davidteather** [comment]
Try to run

pip install requests_oauthlib

If that doesn’t work try

pip3 install requests_oauthlib

**Comment by Enzotoy** [comment]
Thank you it's work ! i have api access error but i think i can resolve them alone (i think xd)
Nice job

**Comment by davidteather** [comment]
No problem if you’ve got any more issues just comment somewhere
